# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "usbhid" "usb_storage" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7724fe86-19f4-45bb-8fed-ee7b7fa02022";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA34-02D8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Host share
  fileSystems."/mnt/share" = {
    device = "share";
    fsType = "9p";
    options = [ "rw" "nofail" "trans=virtio" "version=9p2000.L" "_netdev" "auto" ];
  };
  # fix perms
  fileSystems."/home/kevint/share" = {
    device = "/mnt/share";
    fsType = "fuse.bindfs";
    options = [ "map=501/1000:@20/@1000" "x-systemd.requires=/mnt/share" "_netdev" "nofail" "auto" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
